modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"

[[mods]]
modId = "tweakerge"
version = "${version}"
displayName = "Tweakerge"
displayURL="https://github.com/ThinkingStudios/Tweakeroo-Forge" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
Tweakeroo unofficial (Neo)Forge port.

Adds a bunch of configurable client-side tweaks.
'''

[[mixins]]
config = "mixins.tweakeroo.json"

[[dependencies.tweakerge]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.tweakerge]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.tweakerge]]
modId = "mafglib"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
